<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
  ~
  ~ WSO2 Inc. licenses this file to you under the Apache License,
  ~ Version 2.0 (the "License"); you may not use this file except
  ~ in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<!--<!DOCTYPE assembly [
        <!ELEMENT assembly (formats|includeBaseDirectory|fileSets|dependencySets|files)*>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|excludes|includes|fileMode)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT excludes (exclude)*>
        <!ELEMENT exclude (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes|outputFileNameMapping)*>
        <!ELEMENT outputFileNameMapping (#PCDATA)>
        <!ELEMENT files (file)*>
        <!ELEMENT file (source|outputDirectory|fileMode|destName|filtered)*>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT destName (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        ]>-->
<assembly>
    <id>wso2ei-bin</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <fileSets>
        <fileSet>
            <directory>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/components</directory>
            <outputDirectory>wso2mi-${pom.version}/wso2/components</outputDirectory>
            <excludes>
                <exclude>**/eclipse.ini</exclude>
                <exclude>**/*.lock</exclude>
                <exclude>**/.data</exclude>
                <exclude>**/.settings</exclude>
                <exclude>**/org.wso2.carbon.feature.mgt.ui*</exclude>
                <exclude>**/*.sh</exclude>
                <exclude>**/repository/conf/**</exclude>
                <exclude>**/repository/components/**</exclude>
                <exclude>**/lib/**</exclude>
                <exclude>tmp/**</exclude>
                <exclude>**/bin/**</exclude>
                <exclude>**/Owasp.CsrfGuard.Carbon.properties</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/plugins/saxon_*.jar</exclude>
                <exclude>**/plugins/xalan_*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/conf/tomcat/webapp-classloading-environments.xml</exclude>
                <exclude>**/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/conf/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/wso2/components/plugins/httpclient_4.3.1.wso2v3.jar</exclude>
                <exclude>**/wso2/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/wso2/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/wso2/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar</exclude>
                <exclude>**/wso2/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
                <exclude>**/features/**</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>wso2mi-${pom.version}</outputDirectory>
            <excludes>
                <exclude>**/dbscripts/**</exclude>
                <exclude>repository/database/**</exclude>
                <exclude>**/*.aar</exclude>
                <exclude>**/*.sh</exclude>
                <exclude>**/wso2</exclude>
                <exclude>**/repository/conf/**</exclude>
                <exclude>**/repository/components/**</exclude>
                <exclude>**/wso2/components/**</exclude>
                <exclude>**/lib/**</exclude>
                <exclude>**/bin/**</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/registry.xml</exclude>
                <exclude>**/user-mgt.xml</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/wso2/components/plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/repository/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/repository/conf/registry.xml</exclude>
                <exclude>**/repository/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v3.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/tomcat/carbon/META-INF/context.xml</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
                <exclude>**/repository/resources/conf/**</exclude>
                <exclude>**/repository/resources/security/**</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/conf</directory>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <excludes>
                <exclude>**/wso2</exclude>
                <exclude>**/*.sh</exclude>
                <exclude>**/axis2/axis2.xml</exclude>
                <exclude>**/axis2/tenant-axis2.xml</exclude>
                <exclude>**/synapse.xml</exclude>
                <exclude>**/log4j2.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/registry.xml</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/user-mgt.xml</exclude>
                <exclude>**/repository/conf/etc/logging-bridge.properties</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/tomcat/**</exclude>
                <exclude>**/launch.ini</exclude>
                <exclude>**/deployment.toml</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>./src/resources/config-tool</directory>
            <outputDirectory>wso2mi-${pom.version}/repository/resources/conf</outputDirectory>
            <excludes>
                <exclude>**/carbon.xml.j2</exclude>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/bin</directory>
            <outputDirectory>wso2mi-${pom.version}/bin</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/*.bat</exclude>
                <exclude>**/**bootstrap**</exclude>
                <exclude>**/wrapper.conf</exclude>
                <exclude>build.xml</exclude>
                <exclude>version.txt</exclude>
                <exclude>README.txt</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/diagnostics-tool</directory>
            <outputDirectory>wso2mi-${pom.version}/diagnostics-tool</outputDirectory>
            <excludes>
                <exclude>bin/diagnostics</exclude>
                <exclude>lib/**</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>src/scripts/</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/diagnostics-tool/bin
            </outputDirectory>
            <includes>
                <include>**/diagnostics.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>

        <fileSet>
            <directory>src/conf</directory>
            <outputDirectory>wso2mi-${pom.version}/bin</outputDirectory>
            <includes>
                <include>**.sh</include>
                <include>**.bat</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>

        <fileSet>
            <directory>src/scripts/</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/bin
            </outputDirectory>
            <includes>
                <include>**/build.xml</include>
                <include>**/carbondump.bat</include>
                <include>**/carbondump.sh</include>
                <include>**/chpasswd.bat</include>
                <include>**/chpasswd.sh</include>
                <include>**/tcpmon.bat</include>
                <include>**/tcpmon.sh</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>src/scripts/</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/bin
            </outputDirectory>
            <includes>
                <include>**/build.xml</include>
                <include>**/micro-integrator.bat</include>
                <include>**/fips.bat</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>src/scripts/</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/bin
            </outputDirectory>
            <includes>
                <include>**/tcpmon.sh</include>
                <include>**/micro-integrator.sh</include>
                <include>**/extension-runner.sh</include>
                <include>**/fips.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>

        <fileSet>
            <directory>src/dbscripts</directory>
            <outputDirectory>wso2mi-${pom.version}/dbscripts</outputDirectory>
        </fileSet>

        <fileSet>
            <directory>src/resources/dockerfiles</directory>
            <outputDirectory>wso2mi-${pom.version}/dockerfiles</outputDirectory>
            <excludes>
                <exclude>**/Dockerfile</exclude>
                <exclude>**/.gitkeep</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>src/resources/tomcat</directory>
            <outputDirectory>wso2mi-${pom.version}/conf/tomcat</outputDirectory>
            <includes>
                <include>**/catalina-server.xml</include>
                <include>**/webapp-classloading-environments.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>src/conf</directory>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <includes>
                <include>**/cipher-standalone-config.properties</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                .../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/identity
            </directory>
            <outputDirectory>
                wso2mi-${pom.version}/conf/identity/
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>src/conf/synapse-configs</directory>
            <outputDirectory>wso2mi-${pom.version}/repository/deployment/server/synapse-configs
            </outputDirectory>
            <excludes>
                <exclude>**/empty.txt</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/dropins
            </directory>
            <outputDirectory>wso2mi-${pom.version}/dropins</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/lib
            </directory>
            <outputDirectory>wso2mi-${pom.version}/lib</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>
                target/wso2carbon-core-${carbon.kernel.version}/repository/components/patches
            </directory>
            <outputDirectory>wso2mi-${pom.version}/patches</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>src/resources/capps</directory>
            <outputDirectory>wso2mi-${pom.version}/repository/deployment/server/carbonapps</outputDirectory>
            <excludes>
                <exclude>empty.txt</exclude>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>src/resources/capps</directory>
            <outputDirectory>wso2mi-${pom.version}/repository/deployment/server/apps</outputDirectory>
            <excludes>
                <exclude>empty.txt</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>src/resources/security</directory>
            <outputDirectory>wso2mi-${pom.version}/repository/resources/security</outputDirectory>
            <fileMode>444</fileMode>
        </fileSet>

        <fileSet> <!-- Create empty registry directory -->
            <outputDirectory>wso2mi-${pom.version}/registry</outputDirectory>
            <excludes><exclude>**/*</exclude></excludes>
        </fileSet>
    </fileSets>

    <files>
        <file>
            <source>target/wso2carbon-core-${carbon.kernel.version}/bin/version.txt</source>
            <outputDirectory>wso2mi-${pom.version}/bin/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/wrapper.conf</source>
            <outputDirectory>wso2mi-${pom.version}/bin/yajsw</outputDirectory>
            <destName>wrapper.conf</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/log4j2.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>log4j2.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/carbon.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

<!--        <file>-->
<!--            <source>-->
<!--                ../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/event-broker.xml-->
<!--            </source>-->
<!--            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>-->
<!--            <fileMode>644</fileMode>-->
<!--        </file>-->

        <file>
            <source>
                ../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/data-bridge/data-agent-config.xml
            </source>
            <outputDirectory>wso2mi-${pom.version}/conf/data-bridge</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/axis2.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/axis2</outputDirectory>
            <destName>axis2.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/user-mgt.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>user-mgt.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/axis2_blocking_client.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/axis2</outputDirectory>
            <destName>axis2_blocking_client.xml</destName>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/datasources.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>datasources.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/datasources/master-datasources.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/datasources</outputDirectory>
            <destName>master-datasources.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/access-log.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>access-log.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/internal-apis.xml</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf</outputDirectory>
            <destName>internal-apis.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/carbon.properties</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf</outputDirectory>
            <destName>carbon.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/jndi.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>jndi.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/etc/pax-logging.properties</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/etc/
            </outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/etc/launch.ini</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/etc</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/etc/logging-bridge.properties</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/etc</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/passthru-http.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>passthru-http.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/netty.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>netty.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/synapse.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>synapse.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/file.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>file.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <!-- Cipher Tool Files -->
        <file>
            <source>
                ../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/lib/org.wso2.ciphertool-${cipher.tool.version}.jar
            </source>
            <outputDirectory>${pom.artifactId}-${pom.version}/wso2/lib</outputDirectory>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/synapse-handlers.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>synapse-handlers.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/sequence-observers.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>sequence-observers.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/security/cipher-text.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf/security</outputDirectory>
            <destName>cipher-text.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/security/cipher-tool.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf/security</outputDirectory>
            <destName>cipher-tool.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/security/secret-conf.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf/security</outputDirectory>
            <destName>secret-conf.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/resources/dockerfiles/Dockerfile</source>
            <outputDirectory>wso2mi-${pom.version}/dockerfiles/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/docs/release-notes.xml</source>
            <outputDirectory>wso2mi-${pom.version}</outputDirectory>
            <destName>release-notes.html</destName>
            <fileMode>644</fileMode>
            <filtered>true</filtered>
        </file>
        <file>
            <source>./../LICENSE.txt</source>
            <outputDirectory>wso2mi-${pom.version}</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/README.txt</source>
            <outputDirectory>wso2mi-${pom.version}</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/resources/updates/product.txt</source>
            <outputDirectory>wso2mi-${pom.version}/updates</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>target/wso2carbon-core-${carbon.kernel.version}/bin/README.txt</source>
            <outputDirectory>wso2mi-${pom.version}/bin/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/deployment.toml</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>deployment.toml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/deployment.toml.container</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>deployment.toml.container</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/resources/config-tool/templates/conf/carbon.xml.j2</source>
            <outputDirectory>wso2mi-${pom.version}/repository/resources/conf/templates/conf</outputDirectory>
            <destName>carbon.xml.j2</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/resources/config-tool/templates/diagnostics-tool/conf/config.toml.j2</source>
            <outputDirectory>wso2mi-${pom.version}/repository/resources/conf/templates/diagnostics-tool/conf</outputDirectory>
            <destName>config.toml.j2</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/sec.policy</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>sec.policy</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
    </files>

    <dependencySets>
        <dependencySet>
            <useProjectArtifact>false</useProjectArtifact>
            <outputDirectory>wso2mi-${pom.version}/wso2/lib</outputDirectory>
            <includes>
                <include>org.wso2.ei:org.wso2.micro.integrator.server:jar</include>
                <include>net.sf.saxon:Saxon-HE:jar</include>
                <include>org.wso2.orbit.xerces:xercesImpl:jar</include>
                <include>commons-logging:commons-logging</include>
                <!--
                    woodstox should be in class path to xml builder (need javax.xml.stream.XMLInputFactory
                        implementation to axis2)
                -->
                <include>org.codehaus.woodstox:woodstox-core-asl:jar</include>
                <include>net.consensys.cava:cava-toml:jar</include>
                <include>org.antlr:antlr4-runtime:jar</include>
                <include>com.google.code.gson:gson:jar</include>
                <include>com.google.guava:guava:jar</include>
                <include>org.jsoup:jsoup:jar</include>
                <include>com.google.re2j:re2j:jar</include>
                <include>com.fasterxml.jackson.core:jackson-core:jar</include>
                <include>com.fasterxml.jackson.core:jackson-databind:jar</include>
                <include>com.fasterxml.jackson.core:jackson-annotations:jar</include>
                <include>com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar</include>
                <include>com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar</include>
                <include>com.hubspot.immutables:immutables-exceptions:jar</include>
                <include>commons-codec:commons-codec:jar</include>
                <include>com.hubspot.jinjava:jinjava:jar</include>
                <include>org.bouncycastle:bcpkix-jdk18on:jar</include>
                <include>org.bouncycastle:bcprov-jdk18on:jar</include>
                <include>org.bouncycastle:bcutil-jdk18on:jar</include>
                <include>org.bouncycastle:bctls-jdk18on:jar</include>
                <include>org.slf4j:slf4j-api:jar</include>
                <include>commons-lang.wso2:commons-lang:jar</include>
                <include>org.apache.commons:commons-lang3:jar</include>
                <include>org.wso2.config.mapper:config-mapper:jar</include>
                <include>org.apache.logging.log4j:log4j-api:jar</include>
                <include>org.apache.logging.log4j:log4j-core:jar</include>
                <include>org.apache.logging.log4j:log4j-jcl:jar</include>
                <include>org.slf4j:slf4j-simple:jar</include>
                <include>com.lmax:disruptor:jar</include>
                <include>org.apache.commons:commons-math3:jar</include>
                <include>commons-net:commons-net</include>
                <include>com.github.mwiede:jsch</include>
                <include>org.wso2.runtime.diagnostics:runtime-diagnostics-tool:jar</include>